server:
  port: 8081
spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:8080
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member/(?<path>.*),/$\{path}
eureka:
  client:
    service-url:
      default-zone: http://lokcalhost:8761/eureka

