client:
  kakao-auth:
    url: https://kauth.kakao.com
  kakao:
    url: https://kapi.kakao.com
  apple-auth:
    url: https://appleid.apple.com

social-login:
  provider:
    kakao:
      grant-type: authorization_code
      client-id: YOUR_APP_CLIENT_ID
      client-secret: YOUR_APP_CLIENT_SECRET
    apple:
      grant-type: authorization_code
      client-id: YOUR_APPLE_CLIENT_ID
      key-id: YOUR_APPLE_KEY_ID
      team-id: YOUR_APPLE_TEAM_ID
      audience: https://appleid.apple.com
      private-key: YOUR_APPLE_P8_KEY (-----BEGIN PRIVATE KEY-----, -----END PRIVATE KEY----- 를 제외한 key 문자열을 띄어쓰기 없이 넣어야 합니다)
